- name: install nginx
  yum:
    name: nginx
    state: present

- name: configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: create extra configure dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/nginx/ssl
    - /etc/nginx/htpasswd

- name: copy ssl files
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/ssl/{{ item }}"
    mode: '0644'
  loop:
    - yingzhuo.com.conf
    - yingzhuo.com.crt
    - yingzhuo.com.key

- name: copy password files
  copy:
    src: "yingzhuo.com.password"
    dest: "/etc/nginx/htpasswd/yingzhuo.com.password"
    mode: '0644'
  notify:
    - restart nginx

- name: copy html files
  file:
    path: /data/nginx/yingzhuo.com
    state: directory
    owner: root
    group: root
    mode: '0755'
  notify:
    - restart nginx

- name: sync homepage content
  synchronize:
    mode: push
    src: www
    dest: /data/nginx/yingzhuo.com
    archive: no
    links: no
    recursive: yes
    rsync_opts:
      - "--delete"
      - "--delete-excluded"
      - "--exclude=.DS_Store"
      - "--exclude=.idea*"
      - "--exclude=.git*"
  changed_when: no

- name: copy vhost config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nginx/conf.d/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - www.yingzhuo.com.conf
    - elasticsearch.yingzhuo.com.conf
    - kibana.yingzhuo.com.conf
  notify:
    - restart nginx

- name: mkdir for downloading site
  file:
    path: /data/nginx/yingzhuo.com/download
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: startup nginx
  service:
    name: nginx
    state: started
    enabled: yes
