- name: create group for login
  group:
    name: yingzhuo
    state: present

- name: create user for login
  user:
    name: yingzhuo
    state: present
    group: yingzhuo
    groups:
      - wheel
      - docker
    create_home: yes
    home: /home/yingzhuo
    shell: /usr/bin/zsh
    password: "$6$pUpIT.Ft$f4VhSQrk582YcQBm1MYfW/ytueqM9Xm1XAHixibgrzBpZBUZrILivgPNsWGi.ebdHax9PEWd3JL/Zyh95sYOH."
    system: no
