- name: delete skel dir
  file:
    path: /etc/skel
    state: absent
    force: yes
  changed_when: no

- name: create vim create dir
  file:
    path: "/etc/skel/.vim"
    state: directory
    mode: '0755'
  changed_when: no

- name: unpack vim.tar.gz
  unarchive:
    src: vim.tar.gz
    dest: "/etc/skel/.vim"
    remote_src: no
  changed_when: no

- name: create omz dir
  file:
    path: "/etc/skel/.oh-my-zsh"
    state: directory
    mode: '0755'
  changed_when: no

- name: unpack oh-my-zsh.tar.gz
  unarchive:
    src: oh-my-zsh.tar.gz
    dest: "/etc/skel/.oh-my-zsh"
    remote_src: no
  changed_when: no

- name: reset user and group for skeleton dir
  file:
    path: "/etc/skel"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '0755'
  changed_when: no

- name: copy .zshrc file
  template:
    src: zshrc.j2
    dest: /etc/skel/.zshrc
    backup: no
  changed_when: no