- name: install ncurses and more
  yum:
    name:
      - ncurses-libs
      - ncurses-devel
      - libaio
    state: present

- name: create group for mysqld
  group:
    name: mysql
    state: present

- name: crete user for mysqld
  user:
    name: mysql
    group: mysql
    create_home: no
    shell: /usr/sbin/nologin
    state: present

- name: create data dir
  file:
    path: "{{ item }}"
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'
  with_items:
    - "{{ data_dir_3306 }}"
    - "{{ data_dir_3307 }}"

- name: copy my.conf
  template:
    src: my.cnf.j2
    dest: "{{ config_dir }}/my.cnf"
    owner: root
    group: root
    mode: '0644'

# 注意: --initialize-insecure 指初始化数据库给root用户设置空密码
- name: init data dir
  shell:
    cmd: "{{ item }}"
  with_items:
    - "{{ install_dir }}/bin/mysqld --initialize-insecure --user=mysql --basedir={{ install_dir }} --datadir={{ data_dir_3306 }}"
    - "{{ install_dir }}/bin/mysqld --initialize-insecure --user=mysql --basedir={{ install_dir }} --datadir={{ data_dir_3307 }}"
  ignore_errors: yes
  changed_when: no

- name: setup ssl for mysql
  shell:
    cmd: "{{ item }}"
  with_items:
    - "{{ install_dir }}/bin/mysql_ssl_rsa_setup --datadir={{ data_dir_3306 }}"
    - "{{ install_dir }}/bin/mysql_ssl_rsa_setup --datadir={{ data_dir_3307 }}"
  changed_when: no
