- name: install ncurses and more
  yum:
    name:
      - ncurses-libs
      - ncurses-devel
      - libaio
    state: present

- name: create group for mysqld
  group:
    name: mysql
    state: present

- name: crete user for mysqld
  user:
    name: mysql
    group: mysql
    create_home: no
    shell: /usr/sbin/nologin
    state: present

- name: create config dir
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: copy config file
  template:
    src: my.cnf.j2
    dest: "{{ config_dir }}/my.cnf"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: restart mysqld

- name: create data dir
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'

- name: test if data dir empty
  find:
    paths:
      - "{{ data_dir }}"
  register: files_found

- name: init data dir
  shell:
    cmd: "{{ install_dir }}/bin/mysqld --initialize-insecure --user=mysql --basedir={{ install_dir }} --datadir={{ data_dir }}"
  when: files_found.matched == 0

- name: setup ssl for mysql
  shell:
    cmd: "{{ install_dir }}/bin/mysql_ssl_rsa_setup --datadir={{ data_dir }}"
  changed_when: no

- name: install service
  shell:
    cmd: "cp {{ install_dir }}/support-files/mysql.server /etc/init.d/mysqld"
  changed_when: no

- name: startup mysqld with reboot
  shell:
    cmd: "chkconfig --add mysqld"
  changed_when: no

- name: remove unused config files
  file:
    path: "{{ item }}"
    state: absent
    force: yes
  with_items:
    - /etc/my.cnf
    - /etc/my.cnf.d/

- name: startup mysql
  service:
    name: mysql
    state: started
