- name: install ncurses and more
  yum:
    name:
      - ncurses-libs
      - ncurses-devel
      - libaio
    state: present

- name: create group for mysqld
  group:
    name: mysql
    state: present

- name: crete user for mysqld
  user:
    name: mysql
    group: mysql
    create_home: no
    shell: /usr/sbin/nologin
    state: present

- name: set owner and group for install dir
  file:
    path: "{{ install_dir }}"
    owner: mysql
    group: mysql
    state: directory
    recurse: yes

- name: create config dir
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: copy config file
  template:
    src: my.cnf.j2
    dest: "{{ config_dir }}/my.cnf"
    owner: root
    group: root
    mode: '0644'
    backup: no
  notify: restart mysqld

- name: create data dir
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'

- name: create tmp dir in data dir
  file:
    path: "{{ data_dir }}/tmp"
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'

- name: test if data dir empty
  find:
    paths:
      - "{{ data_dir }}"
  register: files_found

# 注意: --initialize-insecure 指初始化数据库给root用户设置空密码
- name: init data dir
  shell:
    cmd: "{{ install_dir }}/bin/mysqld --initialize-insecure --user=mysql --basedir={{ install_dir }} --datadir={{ data_dir }}"
  when: files_found.matched == 0

- name: setup ssl for mysql
  shell:
    cmd: "{{ install_dir }}/bin/mysql_ssl_rsa_setup --datadir={{ data_dir }}"
  when: files_found.matched == 0

- name: install service
  shell:
    cmd: "cp {{ install_dir }}/support-files/mysql.server /etc/init.d/mysqld"
  changed_when: no

- name: copy validate password dict file
  template:
    src: validate_password.dict.j2
    dest: "{{ data_dir }}/validate_password.dict"
    owner: mysql
    group: mysql
    mode: '0644'
  notify: restart mysqld

- name: startup mysqld with reboot
  shell:
    cmd: "chkconfig --add mysqld"
  changed_when: no

- name: remove unused config files
  file:
    path: "{{ item }}"
    state: absent
    force: yes
  with_items:
    - /etc/my.cnf
    - /etc/my.cnf.d/

- name: startup mysql
  service:
    name: mysql
    state: started

- name: make tool-bin dir
  file:
    path: "{{ install_dir }}/tool-sbin"
    state: directory
    owner: mysql
    group: mysql
    mode: '0755'

- name: copy tools shells
  copy:
    src: "tool-sbin/{{ item }}"
    dest: "{{ install_dir }}/tool-sbin/{{ item }}"
    owner: mysql
    group: mysql
    mode: '0755'
    backup: no
  with_items:
    - mysql-check-non-innodb-tables.sh
    - mysql-check-non-utf8mb4-databases.sh
    - mysql-check-non-utf8mb4-columns.sh
    - mysql-check-users.sh

- name: copy mysql-flush-slow.sh
  template:
    src: tool-sbin/mysql-flush-logs.sh.j2
    dest: "{{ install_dir }}/tool-sbin/mysql-flush-logs.sh"
    owner: mysql
    group: mysql
    mode: '0755'
    backup: no

- name: set crontab for flush log tools
  cron:
    name: "flush mysql logs"
    user: root
    minute: "15"
    hour: "0"
    job: "{{ install_dir }}/tool-sbin/mysql-flush-logs.sh"
    backup: no
