- name: install zabbix-server and more
  yum:
    name:
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-nginx-conf
    state: present

- name: delete old nginx config file
  file:
    path: /etc/nginx/conf.d/zabbix.conf
    state: absent

- name: copy zabbix server config file
  template:
    src: server/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: zabbix
    backup: yes
  notify: restart zabbix-server

- name: copy nginx config file
  template:
    src: nginx/zabbix.yingzhuo.com.conf.j2
    dest: /etc/nginx/conf.d/zabbix.yingzhuo.com.conf
    owner: root
    group: root
    backup: yes
  notify: restart nginx

- name: copy php config file
  template:
    src: php/php.ini.j2
    dest: /etc/php.ini
    owner: root
    group: root
    backup: yes
  notify: restart php

- name: start zabbix-server
  service:
    name: zabbix-server
    state: started
    enabled: yes

- name: start php
  service:
    name: php-fpm
    state: started
    enabled: yes

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes
