- name: install zabbix-server and more
  yum:
    name:
      - zabbix-server-mysql
      - zabbix-get
      - zabbix-sender
      - zabbix-web
      - zabbix-web-mysql
    state: present

- name: copy config file
  template:
    src: server/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart zabbix-server

- name: starup zabbix-server
  service:
    name: zabbix-server
    state: started
    enabled: yes
