- name: install perl-DBI and more
  yum:
    name:
      - perl-DBI
      - perl-DBD-MySQL
    state: present

- name: create percona-toolkit config dir
  file:
    path: /etc/percona-toolkit
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: copy config for all
  template:
    src: percona-toolkit.conf.j2
    dest: /etc/percona-toolkit/percona-toolkit.conf
    owner: root
    group: root
    mode: '0644'
    backup: no
