- name: set base yum source
  yum_repository:
    name: bash
    baseurl: "https://mirrors.aliyun.com/centos/7/os/x86_64/"
    enabled: yes
    gpgcheck: no
    mode: '0644'
    file: bash
    description: base
    state: present
  notify: make cache

- name: set epel yum source
  yum_repository:
    name: epel
    baseurl: "https://mirrors.aliyun.com/epel/7/x86_64/"
    enabled: yes
    gpgcheck: no
    mode: '0644'
    file: epel
    description: epel
    state: present
  notify: make cache
