- name: install vim
  yum:
    name: vim
    state: present

- name: create vim create dir
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - ~/.vim
    - /etc/skel/.vim

- name: unpack vim.tar.gz
  unarchive:
    src: vim.tar.gz
    dest: "{{ item }}"
    remote_src: no
  loop:
    - ~/.vim
    - /etc/skel/.vim
  changed_when: no

- name: reset user and group for vim config files
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: root
    group: root
  loop:
    - ~/.vim
    - /etc/skel/.vim
  changed_when: no